# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::905389665364:role/UdacityFlaskDeployCBKubectlRole
      username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::905389665364:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-P3IS3ILVI92Y
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-22T00:44:46Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1244"
  uid: 6e1003c2-8582-45b8-be0d-c159103f34a0
